// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SZ.PicPaySimplificado.Dados.Contexto;

#nullable disable

namespace SZ.PicPaySimplificado.Dados.Migrations
{
    [DbContext(typeof(PicPaySimplificadoContexto))]
    [Migration("20240831214811_AdicionarCampoDataTransacaoEmTransacaoes")]
    partial class AdicionarCampoDataTransacaoEmTransacaoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SZ.PicPaySimplificado.Dominio.Modelos.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecebedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PagadorId");

                    b.HasIndex("RecebedorId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("SZ.PicPaySimplificado.Dominio.Modelos.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("Saldo")
                        .HasColumnType("real");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SZ.PicPaySimplificado.Dominio.Modelos.Transacao", b =>
                {
                    b.HasOne("SZ.PicPaySimplificado.Dominio.Modelos.Usuario", "Pagador")
                        .WithMany("Transacoes")
                        .HasForeignKey("PagadorId")
                        .IsRequired();

                    b.HasOne("SZ.PicPaySimplificado.Dominio.Modelos.Usuario", "Recebedor")
                        .WithMany()
                        .HasForeignKey("RecebedorId")
                        .IsRequired();

                    b.Navigation("Pagador");

                    b.Navigation("Recebedor");
                });

            modelBuilder.Entity("SZ.PicPaySimplificado.Dominio.Modelos.Usuario", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
